// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Examinationroom is the predicate function for examinationroom builders.
type Examinationroom func(*sql.Selector)

// Nurse is the predicate function for nurse builders.
type Nurse func(*sql.Selector)

// Operative is the predicate function for operative builders.
type Operative func(*sql.Selector)

// Operativerecord is the predicate function for operativerecord builders.
type Operativerecord func(*sql.Selector)

// Tool is the predicate function for tool builders.
type Tool func(*sql.Selector)
