// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/mmildd_s/app/ent/examinationroom"
	"github.com/mmildd_s/app/ent/nurse"
	"github.com/mmildd_s/app/ent/operative"
	"github.com/mmildd_s/app/ent/operativerecord"
	"github.com/mmildd_s/app/ent/schema"
	"github.com/mmildd_s/app/ent/tool"
)

// The init function reads all schema descriptors with runtime
// code (default values, validators or hooks) and stitches it
// to their package variables.
func init() {
	examinationroomFields := schema.Examinationroom{}.Fields()
	_ = examinationroomFields
	// examinationroomDescExaminationroomName is the schema descriptor for examinationroom_name field.
	examinationroomDescExaminationroomName := examinationroomFields[0].Descriptor()
	// examinationroom.ExaminationroomNameValidator is a validator for the "examinationroom_name" field. It is called by the builders before save.
	examinationroom.ExaminationroomNameValidator = examinationroomDescExaminationroomName.Validators[0].(func(string) error)
	nurseFields := schema.Nurse{}.Fields()
	_ = nurseFields
	// nurseDescNurseName is the schema descriptor for nurse_Name field.
	nurseDescNurseName := nurseFields[0].Descriptor()
	// nurse.NurseNameValidator is a validator for the "nurse_Name" field. It is called by the builders before save.
	nurse.NurseNameValidator = nurseDescNurseName.Validators[0].(func(string) error)
	// nurseDescNurseEmail is the schema descriptor for nurse_Email field.
	nurseDescNurseEmail := nurseFields[1].Descriptor()
	// nurse.NurseEmailValidator is a validator for the "nurse_Email" field. It is called by the builders before save.
	nurse.NurseEmailValidator = nurseDescNurseEmail.Validators[0].(func(string) error)
	// nurseDescNursePassword is the schema descriptor for nurse_Password field.
	nurseDescNursePassword := nurseFields[2].Descriptor()
	// nurse.NursePasswordValidator is a validator for the "nurse_Password" field. It is called by the builders before save.
	nurse.NursePasswordValidator = nurseDescNursePassword.Validators[0].(func(string) error)
	// nurseDescNurseTel is the schema descriptor for nurse_Tel field.
	nurseDescNurseTel := nurseFields[3].Descriptor()
	// nurse.NurseTelValidator is a validator for the "nurse_Tel" field. It is called by the builders before save.
	nurse.NurseTelValidator = nurseDescNurseTel.Validators[0].(func(string) error)
	operativeFields := schema.Operative{}.Fields()
	_ = operativeFields
	// operativeDescOperativeName is the schema descriptor for operative_Name field.
	operativeDescOperativeName := operativeFields[0].Descriptor()
	// operative.OperativeNameValidator is a validator for the "operative_Name" field. It is called by the builders before save.
	operative.OperativeNameValidator = operativeDescOperativeName.Validators[0].(func(string) error)
	operativerecordFields := schema.Operativerecord{}.Fields()
	_ = operativerecordFields
	// operativerecordDescOperativeTime is the schema descriptor for OperativeTime field.
	operativerecordDescOperativeTime := operativerecordFields[0].Descriptor()
	// operativerecord.DefaultOperativeTime holds the default value on creation for the OperativeTime field.
	operativerecord.DefaultOperativeTime = operativerecordDescOperativeTime.Default.(func() time.Time)
	toolFields := schema.Tool{}.Fields()
	_ = toolFields
	// toolDescToolName is the schema descriptor for Tool_Name field.
	toolDescToolName := toolFields[0].Descriptor()
	// tool.ToolNameValidator is a validator for the "Tool_Name" field. It is called by the builders before save.
	tool.ToolNameValidator = toolDescToolName.Validators[0].(func(string) error)
}
